spring:
  application:
    name: spring-transaction-demo
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      initial-size: 5
      max-active: 5
#  aop:
#    # 增加@EnableAspectJAutoProxy
#    auto: true
#    # 开启CGLIB代理
#    proxy-target-class: true

# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
